### ISSUE TITLE
Peer Review Milestone1

### ISSUE THREAD

**Issue by sairohithA007** [airavata-courses/CookieArmy#24]
Hi team,

The user interface is good. I liked the bottom navigation bar for rides and the hamburger for providing left pane for other options. Because of these two options, the user interface was self-explanatory.

There are couple of points that I wanted to provide as feedback.
1. The napkin diagram must specify, what a user can do with the application, instead placing a black box mentioning "Application" at the center of diagram.
2. The architecture diagram mentions about APIGateway, but I'm not able to find APIGateway implementation.
3. Other than these I have few feedback points with the setup document and code. They are mentioned in detail in the issues #17 #18 

Thanks,
Sai Rohith Achanta.

**Comment by jkumar10** [comment]
Hi Sai, we appreciate your time and effort in reviewing our project. 
1. We have updated a more detailed version of napkin diagram.
2. Regarding the API gateway, in further phase of the project we are planning to architect a centralized API gateway through message passing that will connect all the other microservices rather than individual REST APIs.
3. We have addressed #17 and #18. 

Thanks.
